version: '3'
services:
    tests:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'pw-tests'
        volumes:
            - ./monocart-results/:/pw-tests/monocart-results/
